In [2]:
import random
from csv import reader
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
def loader(data):
    xvalues = []
    yvalues = []
    for row in data.data:
        xvalues.append(row)
    for row in data.target:
        yvalues.append(row)
    xlist = xvalues[:-50]
    ylist = yvalues[:-50]
    return xlist, ylist

xlist, ylist = loader(data)


In [3]:
dataset = []
for row in xlist:
    for num in row:
        dataset.append(num)
datasete = []
newlist = []
i=0
new_list=[]
while i<len(dataset):
  datasete.append(dataset[i:i+4])
  i+=4
xlist = datasete
xlist        
for i in range(len(xlist)):
    xlist[i].append(ylist[i])
dataset = xlist


In [4]:
random.shuffle(dataset)

In [8]:
def split(dataset):
    train_set = []
    test_set = []
    num = 0
    for row in dataset:
        while num < int(len(dataset)*0.8):
            train_set.append(row)
            num +=1
            break
        while num >= int(len(dataset)*0.8):
            test_set.append(row)
            num += 1
            break
    return train_set, test_set
        
train_set, test_set = split(dataset)   
print(train_set)


[[6.1, 3.0, 4.6, 1.4, 1], [5.5, 2.4, 3.8, 1.1, 1], [5.4, 3.0, 4.5, 1.5, 1], [4.6, 3.2, 1.4, 0.2, 0], [5.7, 3.8, 1.7, 0.3, 0], [5.8, 2.6, 4.0, 1.2, 1], [6.0, 2.2, 4.0, 1.0, 1], [5.0, 2.3, 3.3, 1.0, 1], [4.7, 3.2, 1.3, 0.2, 0], [4.6, 3.1, 1.5, 0.2, 0], [4.6, 3.4, 1.4, 0.3, 0], [6.3, 2.5, 4.9, 1.5, 1], [5.2, 3.5, 1.5, 0.2, 0], [6.1, 2.8, 4.7, 1.2, 1], [5.1, 3.8, 1.9, 0.4, 0], [5.2, 4.1, 1.5, 0.1, 0], [6.0, 3.4, 4.5, 1.6, 1], [4.4, 3.0, 1.3, 0.2, 0], [5.7, 3.0, 4.2, 1.2, 1], [4.9, 3.6, 1.4, 0.1, 0], [5.6, 3.0, 4.5, 1.5, 1], [5.8, 2.7, 4.1, 1.0, 1], [5.1, 3.5, 1.4, 0.2, 0], [5.7, 4.4, 1.5, 0.4, 0], [5.9, 3.2, 4.8, 1.8, 1], [5.5, 2.5, 4.0, 1.3, 1], [6.7, 3.0, 5.0, 1.7, 1], [5.1, 3.5, 1.4, 0.3, 0], [5.8, 4.0, 1.2, 0.2, 0], [4.9, 3.0, 1.4, 0.2, 0], [5.7, 2.8, 4.5, 1.3, 1], [4.9, 3.1, 1.5, 0.2, 0], [4.7, 3.2, 1.6, 0.2, 0], [5.6, 3.0, 4.1, 1.3, 1], [6.6, 3.0, 4.4, 1.4, 1], [5.0, 3.2, 1.2, 0.2, 0], [5.4, 3.9, 1.3, 0.4, 0], [5.0, 3.3, 1.4, 0.2, 0], [6.6, 2.9, 4.6, 1.3, 1], [5.7, 2.6, 3.5, 1.0, 1],

In [16]:
weights = np.zeros(len(train_set[0])-1)
def predict(train, weights, lrn_r, epoch):
    z = 0
    ch_weights = []
    n = 0
    while n<epoch:
        predictions = []
        for row in train:
            f = np.dot(weights, row[:-1])
            yhat = 1.0 if f>z else 0.0
            predictions.append(yhat)
    ####Weights
            for i in range(len(row[:-1])):
                weights[i] += lrn_r*(row[-1]-yhat)*row[i]
                ch_weights.append(weights[i])
        n += 1
    return predictions, ch_weights

predictions, ch_weights = predict(train_set, weights, 0.1, 1000)
len(ch_weights)
predictions
def accuracy(predicted, actual):
    score = 0
    for i in range(len(predicted)):
        if predicted[i] == actual[i]:
            score += 1
    return f"{score/len(actual)*100}%"


def test(test, weights):
    tpred = []
    tactual = [row[-1] for row in test]
    for row in test_set:
        pred = np.dot(row[:-1], weights) 
        tpred.append(0 if pred<0 else 1)
        
    return tpred, tactual


tpred, tactual = test(test_set, weights)

def evaluation(tpred, tacutal):
    tp = 0
    fp = 0
    fn = 0
    tn = 0
    for i in range(len(tactual)):
        if tpred[i] == tactual[i]:
            if tpred[i] == 0:
                tn += 1
            else:
                tp += 1
        else:
            if tpred[i] == 0:
                fn += 1
            else:
                fp += 1
    recall = tp/(tp+fn)
    precision = tp/(tp+fp)
    accuracy = (tp+tn)/(tp+tn+fn+fp)
    f1 = 2*((precision*recall)/(precision+recall))
    return print(f"""Accuracy:  {accuracy}
Precision: {precision}
Recall:    {recall}
F1 Score:  {f1}""")


evaluation(tpred, tactual)

Accuracy:  1.0
Precision: 1.0
Recall:    1.0
F1 Score:  1.0


In [17]:
weights

array([-0.2 , -0.56,  0.76,  0.32])

In [20]:
from sklearn.linear_model import Perceptron

# training the sklearn Perceptron
clf = Perceptron(random_state=None, eta0=0.1, shuffle=False, fit_intercept=False)
clf.fit([row[:-1] for row in train_set], [row[-1] for row in train_set])
y_predict = clf.predict([row[:-1] for row in test_set])

C:\Users\Irena\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [21]:
y_predict

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0])

In [22]:
tpred

[1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0]

In [23]:
weights

array([-0.2 , -0.56,  0.76,  0.32])

In [24]:
clf.coef_

array([[-0.2 , -0.56,  0.76,  0.32]])